Update product-app-dora.yml

diff --git a/.github/workflows/product-app-dora.yml b/.github/workflows/product-app-dora.yml
--- a/.github/workflows/product-app-dora.yml
+++ b/.github/workflows/product-app-dora.yml
@@ -25,8 +25,8 @@ jobs:
         run: pip install -r requirements.txt || echo "No requirements.txt"
 
       - name: Run tests
-       # run: pytest || echo "No tests yet"
-       run: exit 1   # simulate failure
+        run: pytest || echo "No tests yet"
+    #   run: exit 1   # simulate failure
 
       # ----------------------------------------------------------
       # ✅ RANDOMIZED Deployment Report (DORA Deployment)
